chgk_db_generic: &chgk_db_generic
  adapter: mysql
  username: root
  password: geheim
  host: 127.0.0.1
  encoding: utf8

development:
  <<: *chgk_db_generic
  database: chgk_dev
  
test:
  <<: *chgk_db_generic  
  database: chgk_test