development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :domain: gmail.com
  :user_name: ckgkresults
  :password: 34erdfcv
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :domain: gmail.com
  :user_name: ckgkresults
  :password: 34erdfcv
  :enable_starttls_auto: true